plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc
exclude_patterns:
- "config/"
- "script/"
- "**/spec/"
- "**/__tests__/"
- "**/vendor"
- "**/*.d.ts"
- "**/*.test.js"
- "**/*.spec.js"
