import { Platform } from 'react-native';
import {
  IOS_CLIENT_ID,
  ANDROID_CLIENT_ID,
  ANDELA_AUTH_API,
  TYPE,
  PROJECT_ID,
  PRIVATE_KEY_ID,
  PRIVATE_KEY,
  CLIENT_EMAIL,
  CLIENT_ID,
  AUTH_URI,
  TOKEN_URI,
  AUTH_PROVIDER_X509_CERT_URL,
  CLIENT_X509_CERT_URL
} from 'react-native-dotenv';

export default {
  GOOGLE_CLIENT_ID: Platform.select({
    ios: IOS_CLIENT_ID,
    android: ANDROID_CLIENT_ID
  }),
  ANDELA_AUTH_API,
  TYPE,
  PROJECT_ID,
  PRIVATE_KEY_ID,
  PRIVATE_KEY,
  CLIENT_EMAIL,
  CLIENT_ID,
  AUTH_URI,
  TOKEN_URI,
  AUTH_PROVIDER_X509_CERT_URL,
  CLIENT_X509_CERT_URL
};
