export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const FETCHING_EVENTS_SUCCESS = 'FETCHING_EVENTS_SUCCESS';
export const FETCHING_EVENTS_FAILED = 'FETCHING_EVENTS_FAILED';
export const GET_SELECTED_DATE_EVENTS = 'GET_SELECTED_DATE_EVENTS';
export const HANDLE_CALENDAR_MONTH_CHANGE = 'HANDLE_CALENDAR_MONTH_CHANGE';
export const PIN_USERS = 'PIN_USER';
export const UNPIN_USERS = 'UNPIN_USERS';
